version: "3"
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - frontend
  app:
    depends_on:
      - db
      - redis
    build: .
    environment:
      - ENV=development
      - DEBUG=True
      - FLASK_RUN_HOST=127.0.0.1
      - FLASK_RUN_PORT=80
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=mysql://test:test@db:3306/testdb
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
    ports:
      - 80:5000
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
