from env import ENV, DEBUG, FLASK_RUN_HOST, FLASK_RUN_PORT, REDIS_URL, SQLALCHEMY_DATABASE_URI, SQLALCHEMY_TRACK_MODIFICATIONS


class Config:
    ENV = ENV
    DEBUG = DEBUG
    FLASK_RUN_HOST = FLASK_RUN_HOST
    FLASK_RUN_PORT = FLASK_RUN_PORT
    REDIS_URL = REDIS_URL
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = SQLALCHEMY_TRACK_MODIFICATIONS
