from env import ENV, DEBUG, REDIS_URL, SQLALCHEMY_DATABASE_URI, SQLALCHEMY_TRACK_MODIFICATIONS


class Config:
    ENV = ENV
    DEBUG = DEBUG
    REDIS_URL = REDIS_URL
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = SQLALCHEMY_TRACK_MODIFICATIONS
